// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: admin-dynamicasset-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { DynamicAsset, DynamicAssetFilter, DynamicAssetID, DynamicAssetList } from "./dynamic-asset";
import { Empty } from "./google/protobuf/empty";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "dynamicasset";

export interface DynamicAssetStatusMessage {
  DynamicAssetID: string;
  OrganizationID: string;
  Network?: Network | undefined;
}

export interface DynamicAssetAuditFilter {
  DynamicAssetID?: string | undefined;
  OrganizationID?:
    | string
    | undefined;
  /** UserID who made the changes */
  ChangedBy?: string | undefined;
  Network?: Network | undefined;
  Limit?: number | undefined;
  Offset?: number | undefined;
}

function createBaseDynamicAssetStatusMessage(): DynamicAssetStatusMessage {
  return { DynamicAssetID: "", OrganizationID: "", Network: undefined };
}

export const DynamicAssetStatusMessage = {
  encode(message: DynamicAssetStatusMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.DynamicAssetID !== "") {
      writer.uint32(10).string(message.DynamicAssetID);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DynamicAssetStatusMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicAssetStatusMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.DynamicAssetID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicAssetStatusMessage {
    return {
      DynamicAssetID: isSet(object.DynamicAssetID) ? globalThis.String(object.DynamicAssetID) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
    };
  },

  toJSON(message: DynamicAssetStatusMessage): unknown {
    const obj: any = {};
    if (message.DynamicAssetID !== "") {
      obj.DynamicAssetID = message.DynamicAssetID;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicAssetStatusMessage>, I>>(base?: I): DynamicAssetStatusMessage {
    return DynamicAssetStatusMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicAssetStatusMessage>, I>>(object: I): DynamicAssetStatusMessage {
    const message = createBaseDynamicAssetStatusMessage();
    message.DynamicAssetID = object.DynamicAssetID ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.Network = object.Network ?? undefined;
    return message;
  },
};

function createBaseDynamicAssetAuditFilter(): DynamicAssetAuditFilter {
  return {
    DynamicAssetID: undefined,
    OrganizationID: undefined,
    ChangedBy: undefined,
    Network: undefined,
    Limit: undefined,
    Offset: undefined,
  };
}

export const DynamicAssetAuditFilter = {
  encode(message: DynamicAssetAuditFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.DynamicAssetID !== undefined) {
      writer.uint32(10).string(message.DynamicAssetID);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.ChangedBy !== undefined) {
      writer.uint32(26).string(message.ChangedBy);
    }
    if (message.Network !== undefined) {
      writer.uint32(32).int32(message.Network);
    }
    if (message.Limit !== undefined) {
      writer.uint32(40).int32(message.Limit);
    }
    if (message.Offset !== undefined) {
      writer.uint32(48).int32(message.Offset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DynamicAssetAuditFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicAssetAuditFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.DynamicAssetID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.ChangedBy = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Limit = reader.int32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.Offset = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicAssetAuditFilter {
    return {
      DynamicAssetID: isSet(object.DynamicAssetID) ? globalThis.String(object.DynamicAssetID) : undefined,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      ChangedBy: isSet(object.ChangedBy) ? globalThis.String(object.ChangedBy) : undefined,
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
      Limit: isSet(object.Limit) ? globalThis.Number(object.Limit) : undefined,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
    };
  },

  toJSON(message: DynamicAssetAuditFilter): unknown {
    const obj: any = {};
    if (message.DynamicAssetID !== undefined) {
      obj.DynamicAssetID = message.DynamicAssetID;
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.ChangedBy !== undefined) {
      obj.ChangedBy = message.ChangedBy;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Limit !== undefined) {
      obj.Limit = Math.round(message.Limit);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicAssetAuditFilter>, I>>(base?: I): DynamicAssetAuditFilter {
    return DynamicAssetAuditFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicAssetAuditFilter>, I>>(object: I): DynamicAssetAuditFilter {
    const message = createBaseDynamicAssetAuditFilter();
    message.DynamicAssetID = object.DynamicAssetID ?? undefined;
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.ChangedBy = object.ChangedBy ?? undefined;
    message.Network = object.Network ?? undefined;
    message.Limit = object.Limit ?? undefined;
    message.Offset = object.Offset ?? undefined;
    return message;
  },
};

export type AdminDynamicAssetServiceService = typeof AdminDynamicAssetServiceService;
export const AdminDynamicAssetServiceService = {
  /** Create a new dynamic asset */
  create: {
    path: "/dynamicasset.AdminDynamicAssetService/Create",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DynamicAsset) => Buffer.from(DynamicAsset.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DynamicAsset.decode(value),
    responseSerialize: (value: DynamicAssetID) => Buffer.from(DynamicAssetID.encode(value).finish()),
    responseDeserialize: (value: Buffer) => DynamicAssetID.decode(value),
  },
  /** Update an existing dynamic asset */
  update: {
    path: "/dynamicasset.AdminDynamicAssetService/Update",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DynamicAsset) => Buffer.from(DynamicAsset.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DynamicAsset.decode(value),
    responseSerialize: (value: DynamicAssetID) => Buffer.from(DynamicAssetID.encode(value).finish()),
    responseDeserialize: (value: Buffer) => DynamicAssetID.decode(value),
  },
  /** Delete a dynamic asset */
  delete: {
    path: "/dynamicasset.AdminDynamicAssetService/Delete",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DynamicAssetID) => Buffer.from(DynamicAssetID.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DynamicAssetID.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** List dynamic assets with filtering */
  list: {
    path: "/dynamicasset.AdminDynamicAssetService/List",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DynamicAssetFilter) => Buffer.from(DynamicAssetFilter.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DynamicAssetFilter.decode(value),
    responseSerialize: (value: DynamicAssetList) => Buffer.from(DynamicAssetList.encode(value).finish()),
    responseDeserialize: (value: Buffer) => DynamicAssetList.decode(value),
  },
} as const;

export interface AdminDynamicAssetServiceServer extends UntypedServiceImplementation {
  /** Create a new dynamic asset */
  create: handleUnaryCall<DynamicAsset, DynamicAssetID>;
  /** Update an existing dynamic asset */
  update: handleUnaryCall<DynamicAsset, DynamicAssetID>;
  /** Delete a dynamic asset */
  delete: handleUnaryCall<DynamicAssetID, Empty>;
  /** List dynamic assets with filtering */
  list: handleUnaryCall<DynamicAssetFilter, DynamicAssetList>;
}

export interface AdminDynamicAssetServiceClient extends Client {
  /** Create a new dynamic asset */
  create(
    request: DynamicAsset,
    callback: (error: ServiceError | null, response: DynamicAssetID) => void,
  ): ClientUnaryCall;
  create(
    request: DynamicAsset,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DynamicAssetID) => void,
  ): ClientUnaryCall;
  create(
    request: DynamicAsset,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DynamicAssetID) => void,
  ): ClientUnaryCall;
  /** Update an existing dynamic asset */
  update(
    request: DynamicAsset,
    callback: (error: ServiceError | null, response: DynamicAssetID) => void,
  ): ClientUnaryCall;
  update(
    request: DynamicAsset,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DynamicAssetID) => void,
  ): ClientUnaryCall;
  update(
    request: DynamicAsset,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DynamicAssetID) => void,
  ): ClientUnaryCall;
  /** Delete a dynamic asset */
  delete(request: DynamicAssetID, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  delete(
    request: DynamicAssetID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  delete(
    request: DynamicAssetID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** List dynamic assets with filtering */
  list(
    request: DynamicAssetFilter,
    callback: (error: ServiceError | null, response: DynamicAssetList) => void,
  ): ClientUnaryCall;
  list(
    request: DynamicAssetFilter,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DynamicAssetList) => void,
  ): ClientUnaryCall;
  list(
    request: DynamicAssetFilter,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DynamicAssetList) => void,
  ): ClientUnaryCall;
}

export const AdminDynamicAssetServiceClient = makeGenericClientConstructor(
  AdminDynamicAssetServiceService,
  "dynamicasset.AdminDynamicAssetService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): AdminDynamicAssetServiceClient;
  service: typeof AdminDynamicAssetServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
