// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.6
// source: admin-dynamicasset-grpc.proto

package dynamicasset

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminDynamicAssetService_Upsert_FullMethodName = "/dynamicasset.AdminDynamicAssetService/Upsert"
	AdminDynamicAssetService_Delete_FullMethodName = "/dynamicasset.AdminDynamicAssetService/Delete"
	AdminDynamicAssetService_List_FullMethodName   = "/dynamicasset.AdminDynamicAssetService/List"
)

// AdminDynamicAssetServiceClient is the client API for AdminDynamicAssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminDynamicAssetServiceClient interface {
	// Create or update a dynamic asset
	Upsert(ctx context.Context, in *DynamicAsset, opts ...grpc.CallOption) (*DynamicAssetID, error)
	// Delete a dynamic asset
	Delete(ctx context.Context, in *DynamicAssetID, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List dynamic assets with filtering
	List(ctx context.Context, in *DynamicAssetFilter, opts ...grpc.CallOption) (*DynamicAssetList, error)
}

type adminDynamicAssetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminDynamicAssetServiceClient(cc grpc.ClientConnInterface) AdminDynamicAssetServiceClient {
	return &adminDynamicAssetServiceClient{cc}
}

func (c *adminDynamicAssetServiceClient) Upsert(ctx context.Context, in *DynamicAsset, opts ...grpc.CallOption) (*DynamicAssetID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynamicAssetID)
	err := c.cc.Invoke(ctx, AdminDynamicAssetService_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDynamicAssetServiceClient) Delete(ctx context.Context, in *DynamicAssetID, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminDynamicAssetService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDynamicAssetServiceClient) List(ctx context.Context, in *DynamicAssetFilter, opts ...grpc.CallOption) (*DynamicAssetList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynamicAssetList)
	err := c.cc.Invoke(ctx, AdminDynamicAssetService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminDynamicAssetServiceServer is the server API for AdminDynamicAssetService service.
// All implementations should embed UnimplementedAdminDynamicAssetServiceServer
// for forward compatibility.
type AdminDynamicAssetServiceServer interface {
	// Create or update a dynamic asset
	Upsert(context.Context, *DynamicAsset) (*DynamicAssetID, error)
	// Delete a dynamic asset
	Delete(context.Context, *DynamicAssetID) (*emptypb.Empty, error)
	// List dynamic assets with filtering
	List(context.Context, *DynamicAssetFilter) (*DynamicAssetList, error)
}

// UnimplementedAdminDynamicAssetServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminDynamicAssetServiceServer struct{}

func (UnimplementedAdminDynamicAssetServiceServer) Upsert(context.Context, *DynamicAsset) (*DynamicAssetID, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedAdminDynamicAssetServiceServer) Delete(context.Context, *DynamicAssetID) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAdminDynamicAssetServiceServer) List(context.Context, *DynamicAssetFilter) (*DynamicAssetList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminDynamicAssetServiceServer) testEmbeddedByValue() {}

// UnsafeAdminDynamicAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminDynamicAssetServiceServer will
// result in compilation errors.
type UnsafeAdminDynamicAssetServiceServer interface {
	mustEmbedUnimplementedAdminDynamicAssetServiceServer()
}

func RegisterAdminDynamicAssetServiceServer(s grpc.ServiceRegistrar, srv AdminDynamicAssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminDynamicAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminDynamicAssetService_ServiceDesc, srv)
}

func _AdminDynamicAssetService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynamicAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDynamicAssetServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminDynamicAssetService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDynamicAssetServiceServer).Upsert(ctx, req.(*DynamicAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDynamicAssetService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynamicAssetID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDynamicAssetServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminDynamicAssetService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDynamicAssetServiceServer).Delete(ctx, req.(*DynamicAssetID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDynamicAssetService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynamicAssetFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDynamicAssetServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminDynamicAssetService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDynamicAssetServiceServer).List(ctx, req.(*DynamicAssetFilter))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminDynamicAssetService_ServiceDesc is the grpc.ServiceDesc for AdminDynamicAssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminDynamicAssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamicasset.AdminDynamicAssetService",
	HandlerType: (*AdminDynamicAssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _AdminDynamicAssetService_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AdminDynamicAssetService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AdminDynamicAssetService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin-dynamicasset-grpc.proto",
}
