// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.6
// source: dynamic-asset-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { DynamicAsset } from "./dynamic-asset";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "dynamicasset";

export interface UserDynamicAssetRequest {
  OrganizationID: string;
  /** Required: the identifier string (e.g., "news") */
  Identifier: string;
  Network?: Network | undefined;
}

function createBaseUserDynamicAssetRequest(): UserDynamicAssetRequest {
  return { OrganizationID: "", Identifier: "", Network: undefined };
}

export const UserDynamicAssetRequest = {
  encode(message: UserDynamicAssetRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.OrganizationID !== "") {
      writer.uint32(10).string(message.OrganizationID);
    }
    if (message.Identifier !== "") {
      writer.uint32(18).string(message.Identifier);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserDynamicAssetRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserDynamicAssetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Identifier = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserDynamicAssetRequest {
    return {
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Identifier: isSet(object.Identifier) ? globalThis.String(object.Identifier) : "",
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
    };
  },

  toJSON(message: UserDynamicAssetRequest): unknown {
    const obj: any = {};
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Identifier !== "") {
      obj.Identifier = message.Identifier;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserDynamicAssetRequest>, I>>(base?: I): UserDynamicAssetRequest {
    return UserDynamicAssetRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserDynamicAssetRequest>, I>>(object: I): UserDynamicAssetRequest {
    const message = createBaseUserDynamicAssetRequest();
    message.OrganizationID = object.OrganizationID ?? "";
    message.Identifier = object.Identifier ?? "";
    message.Network = object.Network ?? undefined;
    return message;
  },
};

export type UserDynamicAssetServiceService = typeof UserDynamicAssetServiceService;
export const UserDynamicAssetServiceService = {
  /** Get dynamic asset by identifier (e.g., "news", "promotions") */
  getByIdentifier: {
    path: "/dynamicasset.UserDynamicAssetService/GetByIdentifier",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserDynamicAssetRequest) => Buffer.from(UserDynamicAssetRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserDynamicAssetRequest.decode(value),
    responseSerialize: (value: DynamicAsset) => Buffer.from(DynamicAsset.encode(value).finish()),
    responseDeserialize: (value: Buffer) => DynamicAsset.decode(value),
  },
} as const;

export interface UserDynamicAssetServiceServer extends UntypedServiceImplementation {
  /** Get dynamic asset by identifier (e.g., "news", "promotions") */
  getByIdentifier: handleUnaryCall<UserDynamicAssetRequest, DynamicAsset>;
}

export interface UserDynamicAssetServiceClient extends Client {
  /** Get dynamic asset by identifier (e.g., "news", "promotions") */
  getByIdentifier(
    request: UserDynamicAssetRequest,
    callback: (error: ServiceError | null, response: DynamicAsset) => void,
  ): ClientUnaryCall;
  getByIdentifier(
    request: UserDynamicAssetRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DynamicAsset) => void,
  ): ClientUnaryCall;
  getByIdentifier(
    request: UserDynamicAssetRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DynamicAsset) => void,
  ): ClientUnaryCall;
}

export const UserDynamicAssetServiceClient = makeGenericClientConstructor(
  UserDynamicAssetServiceService,
  "dynamicasset.UserDynamicAssetService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): UserDynamicAssetServiceClient;
  service: typeof UserDynamicAssetServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
