// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.6
// source: dynamic-asset-grpc.proto

package dynamicasset

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserDynamicAssetService_GetByIdentifier_FullMethodName = "/dynamicasset.UserDynamicAssetService/GetByIdentifier"
)

// UserDynamicAssetServiceClient is the client API for UserDynamicAssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserDynamicAssetServiceClient interface {
	// Get dynamic asset by identifier (e.g., "news", "promotions")
	GetByIdentifier(ctx context.Context, in *UserDynamicAssetRequest, opts ...grpc.CallOption) (*DynamicAsset, error)
}

type userDynamicAssetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDynamicAssetServiceClient(cc grpc.ClientConnInterface) UserDynamicAssetServiceClient {
	return &userDynamicAssetServiceClient{cc}
}

func (c *userDynamicAssetServiceClient) GetByIdentifier(ctx context.Context, in *UserDynamicAssetRequest, opts ...grpc.CallOption) (*DynamicAsset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynamicAsset)
	err := c.cc.Invoke(ctx, UserDynamicAssetService_GetByIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDynamicAssetServiceServer is the server API for UserDynamicAssetService service.
// All implementations should embed UnimplementedUserDynamicAssetServiceServer
// for forward compatibility.
type UserDynamicAssetServiceServer interface {
	// Get dynamic asset by identifier (e.g., "news", "promotions")
	GetByIdentifier(context.Context, *UserDynamicAssetRequest) (*DynamicAsset, error)
}

// UnimplementedUserDynamicAssetServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserDynamicAssetServiceServer struct{}

func (UnimplementedUserDynamicAssetServiceServer) GetByIdentifier(context.Context, *UserDynamicAssetRequest) (*DynamicAsset, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByIdentifier not implemented")
}
func (UnimplementedUserDynamicAssetServiceServer) testEmbeddedByValue() {}

// UnsafeUserDynamicAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDynamicAssetServiceServer will
// result in compilation errors.
type UnsafeUserDynamicAssetServiceServer interface {
	mustEmbedUnimplementedUserDynamicAssetServiceServer()
}

func RegisterUserDynamicAssetServiceServer(s grpc.ServiceRegistrar, srv UserDynamicAssetServiceServer) {
	// If the following call panics, it indicates UnimplementedUserDynamicAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserDynamicAssetService_ServiceDesc, srv)
}

func _UserDynamicAssetService_GetByIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDynamicAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDynamicAssetServiceServer).GetByIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDynamicAssetService_GetByIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDynamicAssetServiceServer).GetByIdentifier(ctx, req.(*UserDynamicAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserDynamicAssetService_ServiceDesc is the grpc.ServiceDesc for UserDynamicAssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDynamicAssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamicasset.UserDynamicAssetService",
	HandlerType: (*UserDynamicAssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByIdentifier",
			Handler:    _UserDynamicAssetService_GetByIdentifier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dynamic-asset-grpc.proto",
}
