// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: dynamic-asset.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Audit } from "./sologenic/com-fs-utils-lib/models/audit/audit";
import {
  MetaData,
  Network,
  networkFromJSON,
  networkToJSON,
} from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "dynamicasset";

export interface DynamicAssetDetails {
  DynamicAssetID: string;
  Title: string;
  Description: string;
  Identifier: string;
  OrganizationID: string;
  /** Array of asset keys (strings) instead of full asset objects */
  AssetKeys: string[];
}

export interface DynamicAsset {
  DynamicAsset: DynamicAssetDetails | undefined;
  MetaData: MetaData | undefined;
  Audit: Audit | undefined;
}

export interface DynamicAssetID {
  DynamicAssetID: string;
  OrganizationID: string;
  Network?: Network | undefined;
}

export interface DynamicAssetList {
  DynamicAssets: DynamicAsset[];
  Offset?: number | undefined;
  Limit?: number | undefined;
  Total?: number | undefined;
}

export interface DynamicAssetFilter {
  OrganizationID?: string | undefined;
  Identifier?: string | undefined;
  Network?: Network | undefined;
  Limit?: number | undefined;
  Offset?: number | undefined;
}

function createBaseDynamicAssetDetails(): DynamicAssetDetails {
  return { DynamicAssetID: "", Title: "", Description: "", Identifier: "", OrganizationID: "", AssetKeys: [] };
}

export const DynamicAssetDetails = {
  encode(message: DynamicAssetDetails, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.DynamicAssetID !== "") {
      writer.uint32(10).string(message.DynamicAssetID);
    }
    if (message.Title !== "") {
      writer.uint32(18).string(message.Title);
    }
    if (message.Description !== "") {
      writer.uint32(26).string(message.Description);
    }
    if (message.Identifier !== "") {
      writer.uint32(34).string(message.Identifier);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(42).string(message.OrganizationID);
    }
    for (const v of message.AssetKeys) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DynamicAssetDetails {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicAssetDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.DynamicAssetID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Title = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Description = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Identifier = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.AssetKeys.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicAssetDetails {
    return {
      DynamicAssetID: isSet(object.DynamicAssetID) ? globalThis.String(object.DynamicAssetID) : "",
      Title: isSet(object.Title) ? globalThis.String(object.Title) : "",
      Description: isSet(object.Description) ? globalThis.String(object.Description) : "",
      Identifier: isSet(object.Identifier) ? globalThis.String(object.Identifier) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      AssetKeys: globalThis.Array.isArray(object?.AssetKeys)
        ? object.AssetKeys.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: DynamicAssetDetails): unknown {
    const obj: any = {};
    if (message.DynamicAssetID !== "") {
      obj.DynamicAssetID = message.DynamicAssetID;
    }
    if (message.Title !== "") {
      obj.Title = message.Title;
    }
    if (message.Description !== "") {
      obj.Description = message.Description;
    }
    if (message.Identifier !== "") {
      obj.Identifier = message.Identifier;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.AssetKeys?.length) {
      obj.AssetKeys = message.AssetKeys;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicAssetDetails>, I>>(base?: I): DynamicAssetDetails {
    return DynamicAssetDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicAssetDetails>, I>>(object: I): DynamicAssetDetails {
    const message = createBaseDynamicAssetDetails();
    message.DynamicAssetID = object.DynamicAssetID ?? "";
    message.Title = object.Title ?? "";
    message.Description = object.Description ?? "";
    message.Identifier = object.Identifier ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.AssetKeys = object.AssetKeys?.map((e) => e) || [];
    return message;
  },
};

function createBaseDynamicAsset(): DynamicAsset {
  return { DynamicAsset: undefined, MetaData: undefined, Audit: undefined };
}

export const DynamicAsset = {
  encode(message: DynamicAsset, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.DynamicAsset !== undefined) {
      DynamicAssetDetails.encode(message.DynamicAsset, writer.uint32(10).fork()).ldelim();
    }
    if (message.MetaData !== undefined) {
      MetaData.encode(message.MetaData, writer.uint32(18).fork()).ldelim();
    }
    if (message.Audit !== undefined) {
      Audit.encode(message.Audit, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DynamicAsset {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.DynamicAsset = DynamicAssetDetails.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.MetaData = MetaData.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Audit = Audit.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicAsset {
    return {
      DynamicAsset: isSet(object.DynamicAsset) ? DynamicAssetDetails.fromJSON(object.DynamicAsset) : undefined,
      MetaData: isSet(object.MetaData) ? MetaData.fromJSON(object.MetaData) : undefined,
      Audit: isSet(object.Audit) ? Audit.fromJSON(object.Audit) : undefined,
    };
  },

  toJSON(message: DynamicAsset): unknown {
    const obj: any = {};
    if (message.DynamicAsset !== undefined) {
      obj.DynamicAsset = DynamicAssetDetails.toJSON(message.DynamicAsset);
    }
    if (message.MetaData !== undefined) {
      obj.MetaData = MetaData.toJSON(message.MetaData);
    }
    if (message.Audit !== undefined) {
      obj.Audit = Audit.toJSON(message.Audit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicAsset>, I>>(base?: I): DynamicAsset {
    return DynamicAsset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicAsset>, I>>(object: I): DynamicAsset {
    const message = createBaseDynamicAsset();
    message.DynamicAsset = (object.DynamicAsset !== undefined && object.DynamicAsset !== null)
      ? DynamicAssetDetails.fromPartial(object.DynamicAsset)
      : undefined;
    message.MetaData = (object.MetaData !== undefined && object.MetaData !== null)
      ? MetaData.fromPartial(object.MetaData)
      : undefined;
    message.Audit = (object.Audit !== undefined && object.Audit !== null) ? Audit.fromPartial(object.Audit) : undefined;
    return message;
  },
};

function createBaseDynamicAssetID(): DynamicAssetID {
  return { DynamicAssetID: "", OrganizationID: "", Network: undefined };
}

export const DynamicAssetID = {
  encode(message: DynamicAssetID, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.DynamicAssetID !== "") {
      writer.uint32(10).string(message.DynamicAssetID);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DynamicAssetID {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicAssetID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.DynamicAssetID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicAssetID {
    return {
      DynamicAssetID: isSet(object.DynamicAssetID) ? globalThis.String(object.DynamicAssetID) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
    };
  },

  toJSON(message: DynamicAssetID): unknown {
    const obj: any = {};
    if (message.DynamicAssetID !== "") {
      obj.DynamicAssetID = message.DynamicAssetID;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicAssetID>, I>>(base?: I): DynamicAssetID {
    return DynamicAssetID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicAssetID>, I>>(object: I): DynamicAssetID {
    const message = createBaseDynamicAssetID();
    message.DynamicAssetID = object.DynamicAssetID ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.Network = object.Network ?? undefined;
    return message;
  },
};

function createBaseDynamicAssetList(): DynamicAssetList {
  return { DynamicAssets: [], Offset: undefined, Limit: undefined, Total: undefined };
}

export const DynamicAssetList = {
  encode(message: DynamicAssetList, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.DynamicAssets) {
      DynamicAsset.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    if (message.Limit !== undefined) {
      writer.uint32(24).int32(message.Limit);
    }
    if (message.Total !== undefined) {
      writer.uint32(32).int32(message.Total);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DynamicAssetList {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicAssetList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.DynamicAssets.push(DynamicAsset.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Limit = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Total = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicAssetList {
    return {
      DynamicAssets: globalThis.Array.isArray(object?.DynamicAssets)
        ? object.DynamicAssets.map((e: any) => DynamicAsset.fromJSON(e))
        : [],
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
      Limit: isSet(object.Limit) ? globalThis.Number(object.Limit) : undefined,
      Total: isSet(object.Total) ? globalThis.Number(object.Total) : undefined,
    };
  },

  toJSON(message: DynamicAssetList): unknown {
    const obj: any = {};
    if (message.DynamicAssets?.length) {
      obj.DynamicAssets = message.DynamicAssets.map((e) => DynamicAsset.toJSON(e));
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    if (message.Limit !== undefined) {
      obj.Limit = Math.round(message.Limit);
    }
    if (message.Total !== undefined) {
      obj.Total = Math.round(message.Total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicAssetList>, I>>(base?: I): DynamicAssetList {
    return DynamicAssetList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicAssetList>, I>>(object: I): DynamicAssetList {
    const message = createBaseDynamicAssetList();
    message.DynamicAssets = object.DynamicAssets?.map((e) => DynamicAsset.fromPartial(e)) || [];
    message.Offset = object.Offset ?? undefined;
    message.Limit = object.Limit ?? undefined;
    message.Total = object.Total ?? undefined;
    return message;
  },
};

function createBaseDynamicAssetFilter(): DynamicAssetFilter {
  return { OrganizationID: undefined, Identifier: undefined, Network: undefined, Limit: undefined, Offset: undefined };
}

export const DynamicAssetFilter = {
  encode(message: DynamicAssetFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.OrganizationID !== undefined) {
      writer.uint32(10).string(message.OrganizationID);
    }
    if (message.Identifier !== undefined) {
      writer.uint32(18).string(message.Identifier);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    if (message.Limit !== undefined) {
      writer.uint32(32).int32(message.Limit);
    }
    if (message.Offset !== undefined) {
      writer.uint32(40).int32(message.Offset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DynamicAssetFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicAssetFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Identifier = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Limit = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Offset = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicAssetFilter {
    return {
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      Identifier: isSet(object.Identifier) ? globalThis.String(object.Identifier) : undefined,
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
      Limit: isSet(object.Limit) ? globalThis.Number(object.Limit) : undefined,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
    };
  },

  toJSON(message: DynamicAssetFilter): unknown {
    const obj: any = {};
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Identifier !== undefined) {
      obj.Identifier = message.Identifier;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Limit !== undefined) {
      obj.Limit = Math.round(message.Limit);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicAssetFilter>, I>>(base?: I): DynamicAssetFilter {
    return DynamicAssetFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicAssetFilter>, I>>(object: I): DynamicAssetFilter {
    const message = createBaseDynamicAssetFilter();
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.Identifier = object.Identifier ?? undefined;
    message.Network = object.Network ?? undefined;
    message.Limit = object.Limit ?? undefined;
    message.Offset = object.Offset ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
